# Generated by Django 3.1.2 on 2023-02-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50)),
                ('iD', models.PositiveSmallIntegerField()),
                ('edad', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
